// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGmGEhf2j4rsFmKhobMh1I3PooPFilT-k',
    appId: '1:951327074044:web:6f17d0e4bde8dd4ef6d979',
    messagingSenderId: '951327074044',
    projectId: 'd3broomsticks',
    authDomain: 'd3broomsticks.firebaseapp.com',
    databaseURL: 'https://d3broomsticks-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'd3broomsticks.appspot.com',
    measurementId: 'G-NKRM8E5Z83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDevf-G5u7covrfZa22U5Zm5DaLoaiczIM',
    appId: '1:951327074044:android:448c34ad63d921e3f6d979',
    messagingSenderId: '951327074044',
    projectId: 'd3broomsticks',
    databaseURL: 'https://d3broomsticks-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'd3broomsticks.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJRARirl-hjSDK0LPhlC58gPy1sUPJbp4',
    appId: '1:951327074044:ios:f90cf18392edc849f6d979',
    messagingSenderId: '951327074044',
    projectId: 'd3broomsticks',
    databaseURL: 'https://d3broomsticks-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'd3broomsticks.appspot.com',
    iosClientId: '951327074044-0gk6f3e0gsslcpt54shdhpgchqqbjpoh.apps.googleusercontent.com',
    iosBundleId: 'com.roshanpaturkar.d3broomsticks',
  );
}
